### ISSUE TITLE
Error in installation for newer emacs version

### ISSUE THREAD

**Issue by tusharhero** [wyuenho/emacs-pet#34]
**Description**
Error when installing using `use-package` to install.

**Reproduction steps**
1.  Run this:
```elisp
(use-package pet
    :config
    (add-hook 'python-base-mode-hook 'pet-mode -10))
```
2. Error
```
⛔ Error (use-package): pet/:catch: Eager macro-expansion failure: (error "Unsupported QPAT: (\\,@ _)")

```
**Expected behavior**
PET installs and works.

**PET version**
latest
**Emacs version**
GNU Emacs 30.0.50 (build 16, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-02-28

**Desktop (please complete the following information):**
 - OS: Fedora Kionite
 - Version

**Additional context**
It looks like https://github.com/wyuenho/emacs-pet/blob/main/pet.el#L279C8-L279C45 is using incorrect pcase pattern that happens to work by accident. The newer Emacs notices incorrect pattern and throws an error. AFAIU, you can change the pcase pattern to pcase-let ((`(,_ ,action ,file) event)) 
--- @yantar92

**Comment by wyuenho** [comment]
Emacs 30 has not been released yet.

**Comment by tusharhero** [comment]
The fix by yantar92 seems to be simple enough?

**Comment by yantar92** [comment]
Jimmy Yuen Ho Wong ***@***.***> writes:

> Emacs 30 has not been released yet.

Yes, but the code is still just working by chance; because of
undocumented behavior of `pcase-let'.

`(,_ ,action ,file ,@_) pcase pattern is simply invalid.

Let me illustrate using Emacs 28:

(pcase '(foo bar baz test)
  (`(,_ ,action ,file ,@_) (list action file))) ; => nil

As you can see, the pattern you use does not match what you expect.

The correct pattern would be:

(pcase '(foo bar baz test)
  (`(,_ ,action ,file . ,_) (list action file))) ; (bar baz)

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by wyuenho** [comment]
@tusharhero ^ that doesn't look like your PR

**Comment by tusharhero** [comment]
Oh yeah, I just did what they had told me what would fix it in group chat. I have been using the fork myself and it seems to work. But I will try this fix as well to see if it works.
